apiVersion: apps/v1
kind: Deployment
metadata:
  name: request-send
spec:
  replicas: 1
  selector:
    matchLabels:
      app: request-send
  template:
    metadata:
      labels:
        app: request-send
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: request-send
        image: jjnews.azurecr.io/requestsend:300
        resources:
          requests:
            cpu: 1000m
            memory: 1024Mi
          limits:
            cpu: 1500m
            memory: 2048Mi
        ports:
        - containerPort: 8080
        env:
        - name: onenew
          value: "true"
        - name: twonew
          value: "true"
        - name: threenew
          value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: request-send
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: request-send